name              "otrs"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures OTRS"

version           "1.0.0"
supports          "ubuntu"
depends           "accounts"
depends           "apache"
depends           "chef"
depends           "postgresql"
depends           "tools"
