---
driver:
  name: vagrant
  provision: true
  vagrantfiles:
    - .kitchen.provision.rb

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14
  data_bags_path: test/data_bags

platforms:
  # Ubuntu 18.04 is what’s used on the live OSM servers,
  # according to https://hardware.openstreetmap.org/
  - name: ubuntu-18.04
  - name: ubuntu-18.04-ci
    # Driver, transport, and provisioner using Docker and Chef Infra Client,
    # necessary when used on virtual CI boxes that refuse to run Virtualbox or Vagrant.
    # https://github.com/someara/kitchen-dokken
    driver:
      name: dokken
      image: dokken/ubuntu-18.04
      chef_version: 14
      provision: true
      # Docker and systemd need full capabilities granted in privileged mode
      privileged: true
      # Run systemd init to allow services like MySQL, etc. to function
      pid_one_command: /bin/systemd
      intermediate_instructions:
        # Help APT find its required sources on first run
        - RUN /usr/bin/apt-get update -y
    provisioner:
      name: dokken
      product_name: chef
      data_bags_path: test/data_bags
    transport:
      name: dokken

suites:
  - name: accounts
    run_list:
      - recipe[accounts::default]
    excludes: ["ubuntu-18.04-ci"]
  - name: apache
    run_list:
      - recipe[apache::default]
    excludes: ["ubuntu-18.04-ci"]
  - name: apt
    run_list:
      - recipe[apt::default]
  - name: bind
    run_list:
      - recipe[bind::default]
    excludes: ["ubuntu-18.04-ci"]
  - name: blogs
    run_list:
      - recipe[accounts::default]
      - recipe[blogs::default]
    excludes: ["ubuntu-18.04-ci"]
  - name: forum
    run_list:
      - recipe[accounts::default]
      - role[forum]
    excludes: ["ubuntu-18.04-ci"]
  - name: letsencrypt
    run_list:
      - recipe[accounts::default]
      - recipe[apt::default]
      - role[letsencrypt]
    attributes:
      apt:
        sources:
          - openstreetmap
    excludes: ["ubuntu-18.04-ci"]
  - name: munin
    run_list:
      - recipe[munin::default]
    excludes: ["ubuntu-18.04-ci"]
  - name: munin-server
    run_list:
      - recipe[munin::server]
    excludes: ["ubuntu-18.04-ci"]
  - name: mysql
    run_list:
      - recipe[mysql::default]
    excludes: ["ubuntu-18.04-ci"]
  - name: networking
    run_list:
      - recipe[networking::default]
    excludes: ["ubuntu-18.04-ci"]
  - name: otrs
    run_list:
      - recipe[accounts::default]
      - recipe[chef::default]
      - role[otrs]
    excludes: ["ubuntu-18.04-ci"]
  - name: python
    run_list:
      - recipe[python::default]
    excludes: ["ubuntu-18.04-ci"]
  - name: tools
    run_list:
      - recipe[tools::default]
    excludes: ["ubuntu-18.04-ci"]
