inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1

Chef/Modernize/IncludingAptDefaultRecipe:
  Enabled: false
  
Chef/Modernize/CronDFileOrTemplate:
  Enabled: false

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/HeredocIndentation:
  Enabled: true

Naming/MethodParameterName:
  Enabled: false

Style/CommandLiteral:
  EnforcedStyle: percent_x

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/NumericPredicate:
  EnforcedStyle: predicate

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%I': '[]'
    '%w': '[]'
    '%W': '[]'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
