inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Layout/AlignParameters:
  Exclude:
    - '**/metadata.rb'

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/IndentHeredoc:
  EnforcedStyle: squiggly

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets
