inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

ChefModernize/IncludingAptDefaultRecipe:
  Enabled: false

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/IndentHeredoc:
  EnforcedStyle: squiggly

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/NumericPredicate:
  EnforcedStyle: predicate

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%I': '[]'
    '%w': '[]'
    '%W': '[]'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
