name              "community"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures community site"

version           "1.0.0"
supports          "ubuntu"
depends           "accounts"
depends           "docker"
depends           "exim"
depends           "geoipupdate"
depends           "git"
depends           "ssl"
