#!/usr/bin/ruby

require "net/http"
require "uri"

user = gets.chop
pass = gets.chop

request = Net::HTTP::Get.new("/api/0.6/user/details")
request.basic_auth user, pass

response = Net::HTTP.start("api.openstreetmap.org", :use_ssl => true) do |http|
  http.request(request)
end

exit!(0) if response.is_a?(Net::HTTPSuccess)
exit!(1)
