#!/usr/bin/ruby

require "net/http"
require "uri"

user = gets.chop
pass = gets.chop

request = Net::HTTP::Get.new("/api/0.6/user/details")
request.basic_auth user, pass

response = Net::HTTP.new("api.openstreetmap.org").request(request)

exit!(0) if response.kind_of?(Net::HTTPSuccess)
exit!(1)
