name              "hardware"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Configures hardware"

version           "1.0.0"
supports          "ubuntu"
depends           "apt"
depends           "chef"
depends           "git"
depends           "munin"
depends           "prometheus"
depends           "ohai"
depends           "tools"
depends           "sysfs"
