name              "taginfo"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures taginfo"

version           "1.0.0"
supports          "ubuntu"
depends           "accounts"
depends           "apache"
depends           "passenger"
depends           "git"
