name              "piwik"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures Piwik"

version           "1.0.0"
supports          "ubuntu"
depends           "apache"
depends           "geoipupdate"
depends           "mysql"
depends           "php"
