name              "dns"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Configure DNS management"

version           "1.0.0"
supports          "ubuntu"
depends           "accounts"
depends           "apache"
depends           "git"
