name              "tile"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures tile servers"

version           "1.0.0"
supports          "ubuntu"
depends           "accounts"
depends           "apache"
depends           "git"
depends           "munin"
depends           "nodejs"
depends           "postgresql"
depends           "prometheus"
depends           "python"
depends           "systemd"
depends           "tools"
