name              "tile"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures tile servers"
long_description  IO.read(File.join(File.dirname(__FILE__), "README.md"))
version           "1.0.0"
supports          "ubuntu"
depends           "apache"
depends           "git"
depends           "nodejs"
depends           "postgresql"
depends           "python"
depends           "systemd"
depends           "tools"
