name             "apt"
maintainer       "Tom Hughes"
maintainer_email "tom@compton.nu"
license          "Apache-2.0"
description      "Installs/Configures apt"

version          "0.1"
supports         "debian"
supports         "ubuntu"
depends          "accounts"
depends          "apache"
depends          "ssl"
