name              "nginx"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures nginx"

version           "1.0.0"
supports          "ubuntu"
depends           "apt"
depends           "networking"
depends           "prometheus"
depends           "ssl"
depends           "systemd"
