name              "git"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures git"

version           "1.0.0"
supports          "ubuntu"
depends           "accounts"
depends           "apache"
depends           "apt"
depends           "networking"
