name              "stateofthemap"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures State of the Map services"

version           "1.0.0"
supports          "ubuntu"
depends           "apache"
depends           "podman"
depends           "wordpress"
