name              "foundation"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures foundation services"

version           "1.0.0"
supports          "ubuntu"
depends           "apache"
depends           "mediawiki"
depends           "podman"
