name              "dmca"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Configure DMCA form"

version           "1.0.0"
supports          "ubuntu"
depends           "apache"
depends           "php"
