name              "php"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures PHP"

version           "1.0.0"
supports          "ubuntu"
depends           "apache"
depends           "prometheus"
