name              "timescaledb"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures timescaledb"

version           "1.0.0"
supports          "ubuntu"
depends           "apache"
depends           "apt"
depends           "postgresql"
