name              "chef"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures chef"

version           "1.0.0"
supports          "ubuntu"
depends           "apache"
depends           "apt"
depends           "git"
depends           "ohai"
depends           "systemd"
gem               "mail", "= 2.7.1"
