name              "planet"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures a planet server"

version           "1.0.0"
supports          "ubuntu"
depends           "accounts"
depends           "apache"
depends           "apt"
depends           "awscli"
depends           "geoipupdate"
depends           "git"
depends           "ruby"
depends           "osmosis"
depends           "systemd"
