name              "nominatim"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures nominatim servers"

version           "1.0.0"
supports          "ubuntu"
depends           "accounts"
depends           "fail2ban"
depends           "git"
depends           "munin"
depends           "nginx"
depends           "php"
depends           "postgresql"
depends           "python"
depends           "systemd"
