maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache 2.0"
description       "Installs and configures openssh"
version           "1.0.0"
recipe            "openssh", "Installs and configures openssh"
supports          "ubuntu"
depends           "networking"
