name              "gps-tile"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Configures a GPS tile server"

version           "1.0.0"
supports          "ubuntu"
depends           "accounts"
depends           "apache"
depends           "git"
depends           "memcached"
depends           "systemd"
