name              "wordpress"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures Wordpress"

version           "1.0.0"
supports          "ubuntu"
depends           "accounts"
depends           "apache"
depends           "chef"
depends           "fail2ban"
depends           "git"
depends           "mysql"
depends           "php"
depends           "ssl"
gem               "httpclient"
gem               "php_serialize"
