name              "blog"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures Blog services"

version           "1.0.0"
supports          "ubuntu"
depends           "ssl"
depends           "wordpress"
