name              "ntp"
maintainer        "Opscode, Inc."
maintainer_email  "cookbooks@opscode.com"
license           "Apache-2.0"
description       "Installs and configures ntp as a client or server"

version           "0.8.2"
supports          "ubuntu"
depends           "munin"
depends           "systemd"
