name              "apache"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures apache"

version           "1.0.0"
supports          "ubuntu"
depends           "fail2ban"
depends           "prometheus"
depends           "ssl"
depends           "systemd"
