name              "dev"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures dev services"

version           "1.0.0"
supports          "ubuntu"
depends           "apache"
depends           "passenger"
depends           "chef"
depends           "geoipupdate"
depends           "git"
depends           "memcached"
depends           "munin"
depends           "mysql"
depends           "nodejs"
depends           "php"
depends           "postgresql"
depends           "python"
depends           "tools"
depends           "web"
