name              "dev"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures dev services"
long_description  IO.read(File.join(File.dirname(__FILE__), "README.md"))
version           "1.0.0"
supports          "ubuntu"
depends           "apache"
depends           "passenger"
depends           "git"
depends           "mysql"
depends           "nodejs"
depends           "postgresql"
depends           "python"
depends           "tools"
depends           "web"
