name              "dev"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures dev services"

version           "1.0.0"
supports          "ubuntu"
depends           "accounts"
depends           "apache"
depends           "passenger"
depends           "chef"
depends           "geoipupdate"
depends           "git"
depends           "memcached"
depends           "mysql"
depends           "nodejs"
depends           "php"
depends           "podman"
depends           "postgresql"
depends           "python"
depends           "ruby"
depends           "tools"
depends           "web"
