name              "civicrm"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures CiviCRM"
version           "1.0.0"
supports          "ubuntu"
depends           "wordpress"
depends           "mysql"
