name             "devices"
maintainer       "Tom Hughes"
maintainer_email "tom@compton.nu"
license          "Apache-2.0"
description      "Configures devices"
version          "0.1"
supports         "ubuntu"
