name              "web"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures www.openstreetmap.org servers"

version           "1.0.1"
supports          "ubuntu"
depends           "apache"
depends           "passenger"
depends           "git"
depends           "memcached"
depends           "nodejs"
depends           "tools"
depends           "nfs"
depends           "accounts"
depends           "apt"
depends           "systemd"
depends           "geoipupdate"
