default[:networking][:firewall][:enabled] = true
default[:networking][:firewall][:inet] = []
default[:networking][:firewall][:inet6] = []
default[:networking][:firewall][:http_rate_limit] = "-"
default[:networking][:firewall][:http_connection_limit] = "-"
default[:networking][:firewall][:log] = true
default[:networking][:firewall][:mark] = true
default[:networking][:firewall][:raw] = true
default[:networking][:firewall][:mangle] = true
default[:networking][:roles] = {}
default[:networking][:interfaces] = {}
default[:networking][:nameservers] = %w[1.1.1.1 1.0.0.1 2606:4700:4700::1111 2606:4700:4700::1001]
default[:networking][:search] = []
default[:networking][:dnssec] = "allow-downgrade"
default[:networking][:hostname] = node.name
default[:networking][:wireguard][:enabled] = true
default[:networking][:wireguard][:keepalive] = false
default[:networking][:wireguard][:peers] = []
