name              "kibana"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures a kibana server"

version           "1.0.0"
supports          "ubuntu"
depends           "accounts"
depends           "apache"
depends           "systemd"
