name              "dhcpd"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Configures dhcpd"

version           "1.0.0"
supports          "ubuntu"
depends           "networking"
depends           "ntp"
