name              "oxidized"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Configures oxidized to backup equipment configuration"

version           "1.0.0"
supports          "ubuntu"
depends           "accounts"
depends           "git"
depends           "ruby"
