name              "geodns"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures a geographic DNS server"

version           "1.0.0"
supports          "ubuntu"
depends           "geoipupdate"
depends           "networking"
depends           "systemd"
