name              "osqa"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures OSQA"

version           "1.0.0"
supports          "ubuntu"
depends           "accounts"
depends           "apache"
depends           "memcached"
depends           "python"
depends           "tools"
