name              "imagery"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures imagery"
version           "1.0.0"
supports          "ubuntu"
depends           "nginx"
depends           "git"
depends           "systemd"
depends           "ssl"
