#!/usr/bin/perl

=head1 MAGIC MARKERS

  #%# family=snmpauto
  #%# capabilities=snmpconf

=cut

use strict;
use warnings;
use Munin::Plugin::SNMP;

my $session = Munin::Plugin::SNMP->session;

if (defined $ARGV[0] and $ARGV[0] eq "config") {
    my $host = $session->hostname;

    print "host_name $host\n" unless $host eq "localhost";
    print "graph_title Power\n";
    print "graph_args --base 1000 -l 0\n";
    print "graph_vlabel Watts\n";
    print "graph_category power\n";
    print "graph_info This graph shows the power being supplied by the PDU.\n";

    print "power.label Power\n";
    print "power.type GAUGE\n";
    print "power.info Current power draw in watts.\n";
    print "power.draw LINE2\n";
} else {
    my $power = $session->get_single(".1.3.6.1.4.1.318.1.1.26.6.3.1.7.1");

    $power = $power * 10 unless $power eq "U";

    print "power.value ${power}\n";
}
