#!/usr/bin/perl

=head1 MAGIC MARKERS

  #%# family=snmpauto
  #%# capabilities=snmpconf

=cut

use strict;
use warnings;
use Munin::Plugin::SNMP;

my $session = Munin::Plugin::SNMP->session;

if (defined $ARGV[0] and $ARGV[0] eq "config") {
    my $host = $session->hostname;
    my $warning = $session->get_single(".1.3.6.1.4.1.318.1.1.26.6.1.1.6.1");
    my $critical = $session->get_single(".1.3.6.1.4.1.318.1.1.26.6.1.1.7.1");

    print "host_name $host\n" unless $host eq "localhost";
    print "graph_title Load\n";
    print "graph_args --base 1000 -l 0\n";
    print "graph_vlabel Amps\n";
    print "graph_category power\n";
    print "graph_info This graph shows the total throughput the PDU.\n";

    print "current.label Current\n";
    print "current.type GAUGE\n";
    print "current.info Current load in amps.\n";
    print "current.draw LINE2\n";
    print "current.warning ${warning}\n";
    print "current.critical ${critical}\n";
} else {
    my $current = $session->get_single(".1.3.6.1.4.1.318.1.1.26.6.3.1.5.1");

    $current = $current / 10 unless $current eq "U";

    print "current.value ${current}\n";
}
