#!/bin/sh
#
# Plugin to monitor the number of IPs being slowed down by Squid delay pools
# This monitors the number of IPs being delayed in the last 128 pools, which
# are the normal requests.
#
# Parameters:
#
# 	config   (required)
# 	autoconf (optional - used by munin-config)
#

if [ "$1" = "config" ]; then

	echo 'graph_title IPs being delayed with referer'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel IPs'
	echo 'graph_category squid'
	echo 'squid_delay1.label IPs'
	echo 'squid_delay1.min 0'
	echo 'squid_delay1.draw AREA'

	exit 0
fi

req0=`squidclient -h 127.0.0.1 mgr:delay|awk '\$1 == "Pool:"  && \$2 < 128 { pr = 0; } \$1 == "Pool:" && \$2 >= 128 { pr = 1; } { if (pr) { print \$0; } }'|fgrep Current|egrep --count '[0-9]{1,3}:-?[0-9]{1,3} '`

echo "squid_delay1.value " `expr 0 + $req0`
