name             "tilelog"
maintainer       "OpenStreetMap Administrators"
maintainer_email "admins@openstreetmap.org"
license          "Apache-2.0"
description      "Installs and configures tile log analysis"

version          "1.0.0"
supports         "ubuntu"
depends          "accounts"
depends          "planet"
depends          "python"
depends          "systemd"
