name              "mediawiki"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures mediawiki"

version           "1.0.0"
supports          "ubuntu"
depends           "accounts"
depends           "apache"
depends           "apt"
depends           "chef"
depends           "git"
depends           "memcached"
depends           "mysql"
depends           "php"
