name              "db"
maintainer        "OpenStreetMap Administrators"
maintainer_email  "admins@openstreetmap.org"
license           "Apache-2.0"
description       "Installs and configures database servers"

version           "1.0.0"
supports          "ubuntu"
depends           "accounts"
depends           "git"
depends           "postgresql"
depends           "python"
depends           "web"
